name: Validate CSV

on:
  pull_request:
    branches:
    - master
    - main
    - 'release-*.*.*'
#    paths:
#    - 'bundle/*'
    workflow_dispatch:

env:
  OPERATOR_SDK_DL_URL: https://github.com/operator-framework/operator-sdk/releases/download
  OPERATOR_SDK_VERSION: v1.8.0
jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Get Operator SDK
        run: curl -LO ${{ env.OPERATOR_SDK_DL_URL }}/${{ env.OPERATOR_SDK_VERSION }}/operator-sdk_linux_x86_64 && chmod +x operator-sdk_* && mv operator-sdk_linux_x86_64 operator-sdk

      - name: Run Operator SDK
        run: ./operator-sdk version
